### ISSUE TITLE
Artifact in converted .hdr

### ISSUE THREAD

**Issue by elalish** [MONOGRID/gainmap-js#15]
When I converted [this HDR file](https://interactivedemo.withgoogle.com/pixel-8-3d/assets/ARHusky_09.hdr) to JPG using your [tool](https://gainmap-creator.mono-grid.com/), I found it created an artifact at the equirect seam:
<img width="1516" alt="image" src="https://github.com/MONOGRID/gainmap-js/assets/1649964/75e18475-8c15-43d3-9ba2-b1c562636ed1">
As opposed to the correct version with the original .hdr:
<img width="1468" alt="image" src="https://github.com/MONOGRID/gainmap-js/assets/1649964/4ccd53e2-3f34-46da-9637-13c2f679bf36">

**Comment by daniele-pelagatti** [comment]
Interesting, I cannot reproduce this problem if I convert the HDR you posted and then apply it to the example I submitted to three.js.

I'm trying to determine if the bug is coming from the converter (encoding phase) or the library (decoding phase)

This is my converted JPG file (zipped because you never now if online services like github will strip the gain map metadata or not).
[ARHusky_09.zip](https://github.com/MONOGRID/gainmap-js/files/13485819/ARHusky_09.zip), can you try it in your scene and tell me if it still causes the problem?

If it doesn't cause problems then the problem must be in the encoding phase: can you post your converted JPG and maybe tell me the hardware you used to do the conversion? 
If it still causes problems then the problem must be on your usage of the decoder (mipmaps maybe?).

Let's see

**Comment by elalish** [comment]
Thanks, I do see the same problem with your JPG. I tried disabling mipmap generation like your example, but it still repros. Also, why do you disable mipmap generation? That should work fine on a half-float texture, right? 

Also, your JPG does repro the issue for me in the three.js example (I'm on a Macbook Pro, OS 14.1.1):
<img width="1118" alt="image" src="https://github.com/MONOGRID/gainmap-js/assets/1649964/ff913868-cd30-4c2b-a64f-daadb005dbc9">

**Comment by daniele-pelagatti** [comment]
ok good to know it's not a fault in the encoding process (more complicated :D ) , tomorrow I'll try to reproduce the problem on your hardware and, if it's mipMap related then #17 should solve it.

**Comment by daniele-pelagatti** [comment]
> Also, why do you disable mipmap generation? That should work fine on a half-float texture, right?

I do not disable it, rather, I suspect it is enabled where it shouldn't be and this seems to cause problems, #17 allows for complete control over when to enable or disable it and disables it by default, we'll see if this is the case, I'll let you know

**Comment by elalish** [comment]
The plot thickens - this does not repro for me on Safari. My best guess is some kind of undefined behavior in the shader?

**Comment by elalish** [comment]
Also strange, on Chrome I see the error in the background skybox, but not in the PMREM reflection, so I guess this has something to do with the conversion to a cubemap?

**Comment by daniele-pelagatti** [comment]
Alright! 

The problem did not manifest when using `toDataTexture()` in order to generate the background image but I was able to reproduce the problem on your hardware + the dev version of threejs which allows to skip the `toDataTexture()` "hack" in order to use the equirectangular rendertarget as scene background.

I can confirm #17 solves it. I'm not sure exactly why this was happening but the conversion of the `renderTarget.texture` to cubemap suffers when the renderTarget is created with `generateMipmaps = true`, this can be seen at the poles with any texture, including spruit sunrise

this is a comparison of v2.07 vs the upcoming v3.0.0 with #17 applied
### before
```js
hdrJpg = new HDRJPGLoader( renderer )
	.load( 'textures/gainmap/ARHusky_09.jpg', function ( ) {

		hdrJpgPMREMRenderTarget = pmremGenerator.fromEquirectangular( hdrJpg.renderTarget.texture );
		hdrJpgEquirectangularMap = hdrJpg.renderTarget.texture;
		hdrJpgEquirectangularMap.mapping = THREE.EquirectangularReflectionMapping;
		hdrJpgEquirectangularMap.minFilter = THREE.LinearFilter;
		hdrJpgEquirectangularMap.magFilter = THREE.LinearFilter;
		hdrJpgEquirectangularMap.generateMipmaps = false;
		hdrJpg.dispose( false );

	} );
```
![image](https://github.com/MONOGRID/gainmap-js/assets/19731017/ca9a37b2-e78a-4494-82da-6efae8890bf9)
### after
```js
hdrJpg = new HDRJPGLoader( renderer )
        // NEW optional method which allows to specify options
        // including generateMipmaps: true if you are going to use the texture
        // (for example) as an HDR lightmap
        // NOTE: the following line is not needed for the example to work 
        // wrapS/wrapT can be left to THREE.ClampToEdgeWrapping and the background still works
        .setRenderTargetOptions( { wrapS: THREE.RepeatWrapping, wrapT: THREE.RepeatWrapping } )
	.load( 'textures/gainmap/ARHusky_09.jpg', function ( ) {

		hdrJpgPMREMRenderTarget = pmremGenerator.fromEquirectangular( hdrJpg.renderTarget.texture );
		hdrJpgEquirectangularMap = hdrJpg.renderTarget.texture;
		// no need to disable generateMipmaps and specify minFilter
                // they both default to  THREE.LinearFilter
		hdrJpgEquirectangularMap.mapping = THREE.EquirectangularReflectionMapping;
		hdrJpg.dispose( false );

	} );
```
![image](https://github.com/MONOGRID/gainmap-js/assets/19731017/737f35b2-a0e1-468e-8797-aafbee1e8de0)

**Comment by daniele-pelagatti** [comment]
3.0.0 should fix this, let me know otherwise and I'll re-open it
